name = "ChordFinder"
uuid = "95873b58-e1b2-4bef-a070-a5b76e331531"
authors = ["Thomas Poulsen"]
version = "0.1.0"

[compat]
julia = "1.5.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
